"""
tests/test_waf_detector.py
Unit tests untuk WAFDetector — Darkyn SQLi Framework v2.0
"""

import unittest
from unittest.mock import MagicMock, patch

from darkyn.attack.waf_detector import WAFDetector, WAFResult


class TestWAFDetector(unittest.TestCase):

    def setUp(self) -> None:
        self.detector = WAFDetector(timeout=5)

    # ------------------------------------------------------------------
    # WAFResult tests
    # ------------------------------------------------------------------

    def test_waf_result_not_detected_str(self) -> None:
        result = WAFResult(detected=False)
        self.assertEqual(str(result), "No WAF detected")

    def test_waf_result_detected_str(self) -> None:
        result = WAFResult(detected=True, name="Cloudflare", confidence=0.9)
        self.assertIn("Cloudflare", str(result))
        self.assertIn("90%", str(result))

    def test_waf_result_defaults(self) -> None:
        result = WAFResult(detected=False)
        self.assertIsNone(result.name)
        self.assertEqual(result.confidence, 0.0)
        self.assertEqual(result.indicators, [])

    # ------------------------------------------------------------------
    # Detection via mocked response
    # ------------------------------------------------------------------

    def _make_response(
        self,
        headers: dict,
        cookies: dict,
        body: str = "",
    ) -> MagicMock:
        resp = MagicMock()
        resp.headers = headers
        resp.cookies = MagicMock()
        resp.cookies.keys.return_value = list(cookies.keys())
        resp.text = body
        return resp

    def test_detect_cloudflare_by_header(self) -> None:
        resp = self._make_response(
            headers={"cf-ray": "abc123", "Server": "cloudflare"},
            cookies={},
        )
        with patch.object(self.detector._session, "get", return_value=resp):
            result = self.detector.detect("http://example.com")
        self.assertTrue(result.detected)
        self.assertEqual(result.name, "Cloudflare")
        self.assertGreater(result.confidence, 0.3)

    def test_detect_cloudflare_by_cookie(self) -> None:
        resp = self._make_response(
            headers={},
            cookies={"cf_clearance": "abc"},
        )
        with patch.object(self.detector._session, "get", return_value=resp):
            result = self.detector.detect("http://example.com")
        self.assertTrue(result.detected)
        self.assertEqual(result.name, "Cloudflare")

    def test_detect_no_waf(self) -> None:
        resp = self._make_response(
            headers={"Server": "nginx"},
            cookies={},
            body="Hello World",
        )
        with patch.object(self.detector._session, "get", return_value=resp):
            result = self.detector.detect("http://example.com")
        self.assertFalse(result.detected)

    def test_detect_modsecurity_by_body(self) -> None:
        resp = self._make_response(
            headers={},
            cookies={},
            body="This error was generated by Mod_Security",
        )
        with patch.object(self.detector._session, "get", return_value=resp):
            result = self.detector.detect("http://example.com")
        self.assertTrue(result.detected)
        self.assertEqual(result.name, "ModSecurity")

    def test_detect_imperva_by_cookie(self) -> None:
        resp = self._make_response(
            headers={},
            cookies={"incap_ses_123": "value", "visid_incap_456": "value"},
        )
        with patch.object(self.detector._session, "get", return_value=resp):
            result = self.detector.detect("http://example.com")
        self.assertTrue(result.detected)
        self.assertEqual(result.name, "Imperva Incapsula")

    def test_connection_error_raises(self) -> None:
        import requests as req
        with patch.object(
            self.detector._session, "get",
            side_effect=req.RequestException("timeout"),
        ):
            with self.assertRaises(ConnectionError):
                self.detector.detect("http://unreachable.local")

    def test_get_supported_wafs(self) -> None:
        wafs = self.detector.get_supported_wafs()
        self.assertIn("Cloudflare", wafs)
        self.assertIn("ModSecurity", wafs)
        self.assertIn("Akamai", wafs)
        self.assertGreaterEqual(len(wafs), 10)


if __name__ == "__main__":
    unittest.main()
