"""
darkyn/attack/waf_detector.py
WAF Detection Engine — Darkyn SQLi Framework v2.0

Detects WAF presence berdasarkan response headers, cookies,
dan response body signatures. Detection only, tidak ada bypass.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import Optional

import requests


# ---------------------------------------------------------------------------
# Data classes
# ---------------------------------------------------------------------------

@dataclass
class WAFResult:
    """Hasil deteksi WAF pada satu target URL."""

    detected: bool
    name: Optional[str] = None
    confidence: float = 0.0          # 0.0 – 1.0
    indicators: list[str] = field(default_factory=list)

    def __str__(self) -> str:
        if not self.detected:
            return "No WAF detected"
        return (
            f"WAF Detected: {self.name} "
            f"(confidence: {self.confidence:.0%})"
        )


# ---------------------------------------------------------------------------
# Signature database
# ---------------------------------------------------------------------------

# Format: { "WAF Name": { "headers": [...], "cookies": [...], "body": [...] } }
WAF_SIGNATURES: dict[str, dict[str, list[str]]] = {
    "Cloudflare": {
        "headers": ["cf-ray", "cf-cache-status", "cf-request-id"],
        "cookies": ["__cfduid", "cf_clearance"],
        "body":    ["Attention Required! | Cloudflare", "Ray ID:"],
        "server":  ["cloudflare"],
    },
    "ModSecurity": {
        "headers": ["x-modsecurity-action"],
        "cookies": [],
        "body":    ["ModSecurity", "This error was generated by Mod_Security"],
        "server":  [],
    },
    "Akamai": {
        "headers": ["x-check-cacheable", "akamai-origin-hop"],
        "cookies": ["ak_bmsc", "bm_sz"],
        "body":    ["Access Denied", "Reference #"],
        "server":  [],
    },
    "Imperva Incapsula": {
        "headers": ["x-iinfo", "x-cdn"],
        "cookies": ["incap_ses", "visid_incap"],
        "body":    ["Incapsula incident ID", "_Incapsula_Resource"],
        "server":  [],
    },
    "AWS WAF": {
        "headers": ["x-amzn-requestid", "x-amz-cf-id"],
        "cookies": ["aws-waf-token"],
        "body":    ["AWS WAF", "Request blocked"],
        "server":  [],
    },
    "F5 BIG-IP ASM": {
        "headers": ["x-cnection", "x-wa-info"],
        "cookies": ["TS", "TSPD_101"],
        "body":    ["The requested URL was rejected", "Your support ID is"],
        "server":  [],
    },
    "Sucuri": {
        "headers": ["x-sucuri-id", "x-sucuri-cache"],
        "cookies": [],
        "body":    ["Access Denied - Sucuri Website Firewall"],
        "server":  ["sucuri"],
    },
    "Wordfence": {
        "headers": [],
        "cookies": [],
        "body":    ["Generated by Wordfence", "Your access to this site has been limited"],
        "server":  [],
    },
    "Barracuda": {
        "headers": ["x-barracuda-connect"],
        "cookies": ["barra_counter_session"],
        "body":    ["You have been blocked", "Barracuda Web Application Firewall"],
        "server":  [],
    },
    "Fortinet FortiWeb": {
        "headers": ["x-fw-debug"],
        "cookies": [],
        "body":    ["FortiWeb", "Application Firewall"],
        "server":  ["fortigate"],
    },
    "Wallarm": {
        "headers": ["x-wallarm-node"],
        "cookies": [],
        "body":    [],
        "server":  [],
    },
    "Radware AppWall": {
        "headers": ["x-sid"],
        "cookies": [],
        "body":    ["Unauthorized Activity Has Been Detected", "AppWall"],
        "server":  [],
    },
    "Citrix NetScaler": {
        "headers": ["via", "x-nsprotect"],
        "cookies": ["ns_af", "citrix_ns_id"],
        "body":    ["NetScaler", "ns_af="],
        "server":  [],
    },
    "DenyAll": {
        "headers": ["x-denyall"],
        "cookies": ["sessioncookie"],
        "body":    ["Condition Intercepted"],
        "server":  [],
    },
    "Reblaze": {
        "headers": ["x-reblaze-protection"],
        "cookies": ["rbzid"],
        "body":    [],
        "server":  [],
    },
}


# ---------------------------------------------------------------------------
# WAF Detector
# ---------------------------------------------------------------------------

class WAFDetector:
    """
    Deteksi WAF berdasarkan response signature.

    Tidak melakukan bypass, hanya identifikasi vendor WAF
    untuk keperluan reporting dan analisis.

    Args:
        timeout: Request timeout dalam detik.
        user_agent: Custom User-Agent header.
    """

    def __init__(
        self,
        timeout: int = 10,
        user_agent: str = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                          "AppleWebKit/537.36 (KHTML, like Gecko) "
                          "Chrome/124.0.0.0 Safari/537.36",
    ) -> None:
        self.timeout = timeout
        self.user_agent = user_agent
        self._session = requests.Session()
        self._session.headers.update({"User-Agent": self.user_agent})

    def detect(self, url: str, proxy: Optional[str] = None) -> WAFResult:
        """
        Jalankan WAF detection pada target URL.

        Mengirim request normal dan analisis response untuk
        mencocokkan dengan signature WAF yang dikenal.

        Args:
            url: Target URL.
            proxy: Optional proxy URL (e.g. 'http://127.0.0.1:8080').

        Returns:
            WAFResult dengan detail WAF yang terdeteksi.

        Raises:
            requests.RequestException: Jika koneksi ke target gagal.
        """
        proxies = {"http": proxy, "https": proxy} if proxy else None

        try:
            response = self._session.get(
                url,
                timeout=self.timeout,
                proxies=proxies,
                allow_redirects=True,
                verify=False,  # noqa: S501 — pentest context
            )
        except requests.RequestException as exc:
            raise ConnectionError(f"Cannot reach target: {url}") from exc

        return self._analyze_response(response)

    # ------------------------------------------------------------------
    # Internal
    # ------------------------------------------------------------------

    def _analyze_response(self, response: requests.Response) -> WAFResult:
        """Cocokkan response dengan WAF signature database."""

        headers_lower = {k.lower(): v.lower() for k, v in response.headers.items()}
        cookies_lower = {k.lower() for k in response.cookies.keys()}
        body_text     = response.text[:8000]  # Hanya cek 8KB pertama
        server_header = headers_lower.get("server", "")

        best_name: Optional[str] = None
        best_score: float        = 0.0
        best_indicators: list[str] = []

        for waf_name, sigs in WAF_SIGNATURES.items():
            score      = 0.0
            indicators = []
            max_score  = 0.0

            # Headers (bobot tinggi)
            for sig in sigs.get("headers", []):
                max_score += 0.3
                if sig.lower() in headers_lower:
                    score += 0.3
                    indicators.append(f"header:{sig}")

            # Cookies (bobot medium)
            for sig in sigs.get("cookies", []):
                max_score += 0.2
                if any(sig.lower() in c for c in cookies_lower):
                    score += 0.2
                    indicators.append(f"cookie:{sig}")

            # Body (bobot medium)
            for sig in sigs.get("body", []):
                max_score += 0.2
                if sig.lower() in body_text.lower():
                    score += 0.2
                    indicators.append(f"body:{sig[:30]}")

            # Server header (bobot rendah)
            for sig in sigs.get("server", []):
                max_score += 0.1
                if sig.lower() in server_header:
                    score += 0.1
                    indicators.append(f"server:{sig}")

            if max_score == 0 or not indicators:
                continue

            confidence = score / max_score if max_score else 0.0

            if confidence > best_score:
                best_score      = confidence
                best_name       = waf_name
                best_indicators = indicators

        if best_score >= 0.3 and best_name:
            return WAFResult(
                detected    = True,
                name        = best_name,
                confidence  = best_score,
                indicators  = best_indicators,
            )

        return WAFResult(detected=False)

    def get_supported_wafs(self) -> list[str]:
        """Return daftar WAF yang bisa dideteksi."""
        return list(WAF_SIGNATURES.keys())
